// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Financas.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240716194454_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Financas.models.Categorias", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            descricao = "Alimentação",
                            tipo = "Entrada"
                        },
                        new
                        {
                            ID = 2,
                            descricao = "Transporte",
                            tipo = "Entrada"
                        },
                        new
                        {
                            ID = 3,
                            descricao = "Educação",
                            tipo = "Entrada"
                        },
                        new
                        {
                            ID = 4,
                            descricao = "Transporte",
                            tipo = "Entrada"
                        },
                        new
                        {
                            ID = 5,
                            descricao = "Educação",
                            tipo = "Entrada"
                        },
                        new
                        {
                            ID = 6,
                            descricao = "Lazer",
                            tipo = "Entrada"
                        },
                        new
                        {
                            ID = 7,
                            descricao = "Cuidados Pessoais",
                            tipo = "Entrada"
                        },
                        new
                        {
                            ID = 8,
                            descricao = "Investimento",
                            tipo = "Entrada"
                        },
                        new
                        {
                            ID = 9,
                            descricao = "Impostos",
                            tipo = "Entrada"
                        },
                        new
                        {
                            ID = 10,
                            descricao = "Saúde",
                            tipo = "Entrada"
                        },
                        new
                        {
                            ID = 11,
                            descricao = "Outras despesas",
                            tipo = "Entrada"
                        },
                        new
                        {
                            ID = 12,
                            descricao = "Salário",
                            tipo = "Saída"
                        },
                        new
                        {
                            ID = 13,
                            descricao = "Dividendos",
                            tipo = "Saída"
                        },
                        new
                        {
                            ID = 14,
                            descricao = "13° Salário",
                            tipo = "Saída"
                        },
                        new
                        {
                            ID = 15,
                            descricao = "Alugueis",
                            tipo = "Saída"
                        });
                });

            modelBuilder.Entity("Financas.models.Financas.models.Transacoes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("CategoriaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime2");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("valor")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.HasIndex("CategoriaID");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("Financas.models.Usuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<float>("saldo")
                        .HasColumnType("real");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Financas.models.Financas.models.Transacoes", b =>
                {
                    b.HasOne("Financas.models.Categorias", "categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoria");
                });
#pragma warning restore 612, 618
        }
    }
}
